### ISSUE TITLE
Debian Base Image has been updated

### ISSUE THREAD

**Issue by tomschlenkhoff** [fluent/fluent-bit-docker-image#14]
FROM gcr.io/google-containers/debian-base-amd64:0.4.0 as builder

**Comment by edsiper** [comment]
@tomschlenkhoff thanks. do you know where is the changelog or release notes ?

**Comment by tomschlenkhoff** [comment]
I spent a few minutes googling/looking around, but found nothing resembling a changelog. Looks like we have to trust google to do the right thing (tm).

**Comment by edsiper** [comment]
not longer applicable since we use distroless
