### ISSUE TITLE
kube exec does not work for fluent/fluent-bit:1.6.0

### ISSUE THREAD

**Issue by Arpan-Chakra** [fluent/fluent-bit-docker-image#37]
Hi, Facing issue in running shell or bash using kube exec into fluent bit daemon set in kubernetes.

Following errors faced 

Command : k exec -it fluent-bit-9vsqp -n monitoring -- /bin/sh
Error: OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
command terminated with exit code 126

Command : k exec -it fluent-bit-9vsqp -n monitoring -- bash
Error : OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
command terminated with exit code 126

Command: k exec -it fluent-bit-9vsqp -n monitoring -- sh
Error: OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
command terminated with exit code 126

**Comment by jalkjaer** [comment]
Only the debug version of the images includes a shell  (busybox)
i.e.
```
docker run --rm fluent/fluent-bit:1.6.9 sh --help
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown.
```
vs debug image:
```
docker run  --rm  fluent/fluent-bit:1.6.9-debug sh --help
BusyBox v1.31.1 (2020-06-02 02:36:36 UTC) multi-call binary.

Usage: sh [-/+OPTIONS] [-/+o OPT]... [-c 'SCRIPT' [ARG0 [ARGS]] / FILE [ARGS] / -s [ARGS]]

Unix shell interpreter
```
Hint: You can use `docker export <container name/id> | tar t` to get a listing of the files in the container
